#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(MotionPlatformWindowLayout, "MotionPlatformDebugWindow.layout");
class MotionPlatformWindowLayout : public wraps::BaseLayout
{

public:

	MotionPlatformWindowLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~MotionPlatformWindowLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(MotionPlatformWindowLayout, m_window, "window");
	MyGUI::Window* m_window;

	ATTRIBUTE_FIELD_WIDGET_NAME(MotionPlatformWindowLayout, m_text_panel, "text_panel");
	MyGUI::EditBox* m_text_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(MotionPlatformWindowLayout, m_yaw_icon, "yaw_icon");
	MyGUI::ImageBox* m_yaw_icon;

	ATTRIBUTE_FIELD_WIDGET_NAME(MotionPlatformWindowLayout, m_pitch_icon, "pitch_icon");
	MyGUI::ImageBox* m_pitch_icon;

	ATTRIBUTE_FIELD_WIDGET_NAME(MotionPlatformWindowLayout, m_roll_icon, "roll_icon");
	MyGUI::ImageBox* m_roll_icon;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

