#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorFlaresPanelLayout, "rig_editor_flares_panel.layout");
class RigEditorFlaresPanelLayout : public wraps::BaseLayout
{

public:

	RigEditorFlaresPanelLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorFlaresPanelLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_flares_panel, "flares_panel");
	MyGUI::Window* m_flares_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_ref_node_label, "ref_node_label");
	MyGUI::TextBox* m_ref_node_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_ref_node_editbox, "ref_node_editbox");
	MyGUI::EditBox* m_ref_node_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_ref_node_set_button, "ref_node_set_button");
	MyGUI::Button* m_ref_node_set_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_x_node_label, "x_node_label");
	MyGUI::TextBox* m_x_node_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_x_node_editbox, "x_node_editbox");
	MyGUI::EditBox* m_x_node_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_x_node_set_button, "x_node_set_button");
	MyGUI::Button* m_x_node_set_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_y_node_label, "y_node_label");
	MyGUI::TextBox* m_y_node_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_y_node_editbox, "y_node_editbox");
	MyGUI::EditBox* m_y_node_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_y_node_set_button, "y_node_set_button");
	MyGUI::Button* m_y_node_set_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_swap_xy_nodes_button, "swap_xy_nodes_button");
	MyGUI::Button* m_swap_xy_nodes_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_size_label, "size_label");
	MyGUI::TextBox* m_size_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_size_editbox, "size_editbox");
	MyGUI::EditBox* m_size_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_x_offset_label, "x_offset_label");
	MyGUI::TextBox* m_x_offset_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_y_offset_label, "y_offset_label");
	MyGUI::TextBox* m_y_offset_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_z_offset_label, "z_offset_label");
	MyGUI::TextBox* m_z_offset_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_materialflarebinding_label, "materialflarebinding_label");
	MyGUI::TextBox* m_materialflarebinding_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_control_number_label, "control_number_label");
	MyGUI::TextBox* m_control_number_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_tooltip_label, "tooltip_label");
	MyGUI::TextBox* m_tooltip_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_x_offset_editbox, "x_offset_editbox");
	MyGUI::EditBox* m_x_offset_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_y_offset_editbox, "y_offset_editbox");
	MyGUI::EditBox* m_y_offset_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_z_offset_editbox, "z_offset_editbox");
	MyGUI::EditBox* m_z_offset_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_size_scale_button, "size_scale_button");
	MyGUI::Button* m_size_scale_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_grab_button, "grab_button");
	MyGUI::Button* m_grab_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_flare_material_label, "flare_material_label");
	MyGUI::TextBox* m_flare_material_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_flare_material_editbox, "flare_material_editbox");
	MyGUI::EditBox* m_flare_material_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_materialflarebinding_editbox, "materialflarebinding_editbox");
	MyGUI::EditBox* m_materialflarebinding_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_flare_material_reset_button, "flare_material_reset_button");
	MyGUI::Button* m_flare_material_reset_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_type_label, "type_label");
	MyGUI::TextBox* m_type_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_type_combobox, "type_combobox");
	MyGUI::ComboBox* m_type_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_control_number_combobox, "control_number_combobox");
	MyGUI::ComboBox* m_control_number_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_blink_delay_label, "blink_delay_label");
	MyGUI::TextBox* m_blink_delay_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorFlaresPanelLayout, m_blink_delay_editbox, "blink_delay_editbox");
	MyGUI::EditBox* m_blink_delay_editbox;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

