
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "GUI_MotionPlatformWindowLayout.h"

using namespace RoR;
using namespace GUI;

MotionPlatformWindowLayout::MotionPlatformWindowLayout(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

MotionPlatformWindowLayout::~MotionPlatformWindowLayout()
{
}

